# Generated by Django 5.2.9 on 2026-01-01 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0003_usermarket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(choices=[('24H', '24 Hours'), ('30D', '30 Days'), ('12W', '12 Weeks'), ('12M', '12 Months'), ('ANY', 'Any Horizon')], default='ANY', max_length=10)),
                ('condition_type', models.CharField(choices=[('direction_change', 'Direction Changes'), ('direction_up', 'Direction is Up'), ('direction_down', 'Direction is Down'), ('confidence_above', 'Confidence Above'), ('confidence_below', 'Confidence Below'), ('expected_move_above', 'Expected Move Above'), ('expected_move_below', 'Expected Move Below'), ('price_above', 'Price Above'), ('price_below', 'Price Below')], max_length=30)),
                ('condition_value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('triggered', 'Triggered')], default='active', max_length=20)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='markets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('condition_met', models.CharField(max_length=200)),
                ('forecast_value', models.CharField(max_length=100)),
                ('email_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alert')),
            ],
            options={
                'db_table': 'alert_history',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
