# Generated by Django 5.2.9 on 2025-12-30 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasts', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('horizon', models.CharField(default='daily', max_length=20)),
                ('trigger_type', models.CharField(choices=[('confidence_above', 'Confidence Above'), ('confidence_below', 'Confidence Below'), ('prob_up_above', 'Probability Up Above'), ('prob_down_above', 'Probability Down Above'), ('move_above', 'Predicted Move Above'), ('direction_change', 'Direction Change')], max_length=30)),
                ('trigger_value', models.FloatField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], default='email', max_length=20)),
                ('webhook_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('cooldown_hours', models.IntegerField(default=24)),
                ('max_alerts_per_day', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='markets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_value_at_time', models.FloatField()),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True)),
                ('message', models.TextField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alert')),
                ('forecast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='forecasts.forecast')),
            ],
            options={
                'db_table': 'alert_history',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
