# Generated by Django 5.2.9 on 2026-01-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='notify_email',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='notify_push',
        ),
        migrations.AlterField(
            model_name='alert',
            name='condition_type',
            field=models.CharField(choices=[('direction_change', 'Direction Changes'), ('direction_up', 'Direction is Up'), ('direction_down', 'Direction is Down'), ('confidence_above', 'Confidence Above'), ('confidence_below', 'Confidence Below'), ('expected_move_above', 'Expected Move Above'), ('expected_move_below', 'Expected Move Below')], max_length=30),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20),
        ),
    ]
