# Generated by Django 5.2.9 on 2025-12-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('equity', 'Equity'), ('forex', 'Forex'), ('commodity', 'Commodity')], default='crypto', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('data_source', models.CharField(default='binance', max_length=50)),
                ('data_source_symbol', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_data_fetch', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'markets',
                'ordering': ['symbol'],
            },
        ),
    ]
