# Generated by Django 5.2.9 on 2025-12-30 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('equity', 'Equity'), ('forex', 'Forex'), ('commodity', 'Commodity')], default='crypto', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('data_source', models.CharField(default='binance', max_length=50)),
                ('data_source_symbol', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_data_fetch', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'markets',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
                ('timeframe', models.CharField(default='1h', max_length=10)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='markets.market')),
            ],
            options={
                'db_table': 'market_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['market', 'timestamp'], name='market_data_market__8e2cd3_idx'), models.Index(fields=['market', 'timeframe', 'timestamp'], name='market_data_market__efd71a_idx')],
                'unique_together': {('market', 'timestamp', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='UserMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by_users', to='markets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_markets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_markets',
                'ordering': ['-is_favorite', '-added_at'],
                'unique_together': {('user', 'market')},
            },
        ),
    ]
