# Generated by Django 5.2.9 on 2025-12-31 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('timeframe', models.CharField(default='1h', max_length=10)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='markets.market')),
            ],
            options={
                'db_table': 'market_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['market', 'timeframe', 'timestamp'], name='market_data_market__efd71a_idx')],
                'unique_together': {('market', 'timestamp', 'timeframe')},
            },
        ),
    ]
