# Generated by Django 5.2.9 on 2025-12-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('horizon', models.CharField(choices=[('24H', '24 Hours'), ('30D', '30 Days'), ('12W', '12 Weeks'), ('12M', '12 Months')], max_length=10)),
                ('status', models.CharField(choices=[('training', 'Training'), ('candidate', 'Candidate'), ('production', 'Production'), ('deprecated', 'Deprecated')], default='candidate', max_length=20)),
                ('training_started_at', models.DateTimeField(blank=True, null=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('training_data_start', models.DateField(blank=True, null=True)),
                ('training_data_end', models.DateField(blank=True, null=True)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('directional_accuracy', models.FloatField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version', 'horizon')},
            },
        ),
    ]
