# Generated by Django 5.2.9 on 2025-12-30 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('training', 'Training'), ('candidate', 'Candidate'), ('production', 'Production'), ('deprecated', 'Deprecated')], default='candidate', max_length=20)),
                ('training_started_at', models.DateTimeField(blank=True, null=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('training_data_start', models.DateField(blank=True, null=True)),
                ('training_data_end', models.DateField(blank=True, null=True)),
                ('supports_hourly', models.BooleanField(default=True)),
                ('supports_daily', models.BooleanField(default=True)),
                ('supports_weekly', models.BooleanField(default=True)),
                ('supports_monthly', models.BooleanField(default=True)),
                ('artifact_path', models.CharField(max_length=500)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('directional_accuracy', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(choices=[('hourly', 'Hourly (24H)'), ('daily', 'Daily (7D)'), ('weekly', 'Weekly (4W)'), ('monthly', 'Monthly (12M)')], max_length=20)),
                ('generated_at', models.DateTimeField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('probability_up', models.FloatField()),
                ('probability_down', models.FloatField()),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('predicted_low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('predicted_mid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('predicted_high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='markets.market')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasts.mlmodel')),
            ],
            options={
                'db_table': 'forecasts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(max_length=20)),
                ('test_start', models.DateField()),
                ('test_end', models.DateField()),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mape', models.FloatField()),
                ('directional_accuracy', models.FloatField()),
                ('calibration_score', models.FloatField(blank=True, null=True)),
                ('regime_metrics', models.JSONField(default=dict)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='markets.market')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='forecasts.mlmodel')),
            ],
            options={
                'db_table': 'backtest_runs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('predicted_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('confidence_low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('confidence_high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('confidence_score', models.FloatField()),
                ('actual_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='forecasts.forecast')),
            ],
            options={
                'db_table': 'forecast_points',
                'ordering': ['step'],
                'unique_together': {('forecast', 'step')},
            },
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['market', 'horizon', 'is_latest'], name='forecasts_market__74328e_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['market', 'horizon', 'generated_at'], name='forecasts_market__52d11b_idx'),
        ),
    ]
