# Generated by Django 5.2.9 on 2025-12-31 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
        ('markets', '0002_marketdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(choices=[('24H', '24 Hours'), ('30D', '30 Days'), ('12W', '12 Weeks'), ('12M', '12 Months')], max_length=10)),
                ('generated_at', models.DateTimeField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('predicted_low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('predicted_mid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('predicted_high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='markets.market')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasts.mlmodel')),
            ],
            options={
                'db_table': 'forecasts',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['market', 'horizon', 'is_latest'], name='forecasts_market__74328e_idx'), models.Index(fields=['market', 'horizon', 'generated_at'], name='forecasts_market__52d11b_idx')],
            },
        ),
    ]
