# Generated by Django 5.2.9 on 2025-12-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_forecast'),
        ('markets', '0003_usermarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(max_length=10)),
                ('test_start', models.DateField()),
                ('test_end', models.DateField()),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mape', models.FloatField()),
                ('directional_accuracy', models.FloatField()),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_directions', models.IntegerField(default=0)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='markets.market')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='forecasts.mlmodel')),
            ],
            options={
                'db_table': 'backtest_runs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('predicted_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('confidence_low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('confidence_high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('confidence_score', models.FloatField()),
                ('actual_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='forecasts.forecast')),
            ],
            options={
                'db_table': 'forecast_points',
                'ordering': ['step'],
                'unique_together': {('forecast', 'step')},
            },
        ),
    ]
