# Generated by Django 5.2.9 on 2025-12-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_backtestrun_forecastpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='bias',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='correlation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='max_error',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='median_ae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='r2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
