# Generated by Django 5.2.9 on 2026-01-08 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0004_mlmodel_bias_mlmodel_correlation_mlmodel_max_error_and_more'),
        ('markets', '0003_usermarket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='markets.market'),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('xgboost', 'XGBoost'), ('lstm', 'LSTM')], default='xgboost', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='mlmodel',
            constraint=models.UniqueConstraint(fields=('model_type', 'horizon', 'market', 'version'), name='unique_model_version'),
        ),
    ]
