# Generated by Django 5.2.9 on 2026-01-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_alter_mlmodel_unique_together_mlmodel_market_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastpoint',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='forecastpoint',
            unique_together={('forecast', 'timestamp')},
        ),
    ]
