export const DISCLAIMER_SECTIONS = [
  {
    id: "general",
    title: "1. General Disclaimer",
    content: `The information provided by Nordict ("we," "us," or "our") on our website, applications, and services (collectively, the "Service") is for general informational purposes only.

All information on the Service is provided in good faith. However, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Service.

Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Service or reliance on any information provided. Your use of the Service and your reliance on any information is solely at your own risk.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z"
        />
      </svg>
    ),
  },
  {
    id: "no-financial-advice",
    title: "2. No Financial Advice",
    content: `THE SERVICE DOES NOT PROVIDE FINANCIAL, INVESTMENT, TRADING, TAX, LEGAL, OR ACCOUNTING ADVICE.

Nothing contained on the Service constitutes a solicitation, recommendation, endorsement, or offer by Nordict or any third party to buy or sell any securities, cryptocurrencies, or other financial instruments.

Our forecasts, predictions, and analyses are:
- Generated by machine learning models based on historical data
- Provided for informational and educational purposes only
- Not personalized investment recommendations
- Not a substitute for professional financial advice

You should always conduct your own research and consult with qualified financial professionals before making any investment decisions.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
        />
      </svg>
    ),
  },
  {
    id: "forecast-accuracy",
    title: "3. Forecast Accuracy",
    content: `While we strive to provide accurate and useful forecasts, we cannot and do not guarantee the accuracy of any predictions or analyses.

Important considerations:
- Past performance is not indicative of future results
- Historical accuracy rates may not persist in future market conditions
- Confidence scores reflect model uncertainty, not guaranteed outcomes
- Market conditions can change rapidly and unpredictably
- Black swan events and unforeseen circumstances can invalidate any forecast

Our published accuracy metrics are based on historical backtesting and live performance tracking. These metrics are provided for transparency but should not be interpreted as guarantees of future performance.

We recommend treating our forecasts as one of many inputs in your decision-making process, not as definitive predictions.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z"
        />
      </svg>
    ),
  },
  {
    id: "risk-disclosure",
    title: "4. Risk Disclosure",
    content: `Trading and investing in cryptocurrencies and digital assets involves substantial risk of loss and is not suitable for all investors.

Key risks include:
- Extreme price volatility — prices can fluctuate dramatically in short periods
- Market manipulation — cryptocurrency markets may be subject to manipulation
- Regulatory uncertainty — laws and regulations may change unpredictably
- Technical risks — smart contract bugs, exchange hacks, wallet vulnerabilities
- Liquidity risks — some assets may be difficult to buy or sell at desired prices
- Total loss — you can lose your entire investment

You should carefully consider your investment objectives, level of experience, and risk appetite before using our Service. Never invest more than you can afford to lose.

The cryptocurrency market operates 24/7 and can experience significant movements while you are unable to monitor or react to market conditions.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
        />
      </svg>
    ),
  },
  {
    id: "no-guarantees",
    title: "5. No Guarantees",
    content: `We make no guarantees or promises regarding:

- The profitability of any trades or investments
- The accuracy of any specific forecast or prediction
- The continued availability or performance of the Service
- The timeliness of forecast updates or alerts
- The suitability of our Service for your specific needs

The Service is provided "as is" and "as available" without any warranties of any kind, whether express, implied, or statutory, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.

Any testimonials, case studies, or examples of past performance are not guarantees of future results and may not reflect the experience of all users.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
        />
      </svg>
    ),
  },
  {
    id: "third-party",
    title: "6. Third-Party Content and Links",
    content: `The Service may contain links to third-party websites, content, or services that are not owned or controlled by Nordict.

We have no control over, and assume no responsibility for:
- The content, privacy policies, or practices of third-party sites
- The accuracy or reliability of third-party information
- Any products or services offered by third parties
- Any loss or damage arising from your use of third-party services

Any reference to third-party products, services, or information does not constitute an endorsement or recommendation by Nordict.

We strongly advise you to read the terms and conditions and privacy policies of any third-party websites or services that you visit or use.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"
        />
      </svg>
    ),
  },
  {
    id: "limitation-liability",
    title: "7. Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL NORDICT, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR:

- Any indirect, incidental, special, consequential, or punitive damages
- Any loss of profits, revenue, data, or business opportunities
- Any trading or investment losses, regardless of cause
- Any damages arising from your use of or inability to use the Service
- Any damages arising from unauthorized access to your account

This limitation applies whether the alleged liability is based on contract, tort, negligence, strict liability, or any other basis, even if we have been advised of the possibility of such damage.

Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability, so some of the above limitations may not apply to you.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M12 9v3.75m0-10.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.75c0 5.592 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.57-.598-3.75h-.152c-3.196 0-6.1-1.249-8.25-3.286zm0 13.036h.008v.008H12v-.008z"
        />
      </svg>
    ),
  },
  {
    id: "indemnification",
    title: "8. Indemnification",
    content: `You agree to defend, indemnify, and hold harmless Nordict and its officers, directors, employees, contractors, agents, licensors, and suppliers from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to:

- Your violation of this Disclaimer or our Terms of Service
- Your use of the Service
- Your trading or investment decisions
- Any content you submit or transmit through the Service
- Your violation of any rights of a third party

This indemnification obligation will survive the termination of your account and your use of the Service.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z"
        />
      </svg>
    ),
  },
  {
    id: "changes",
    title: "9. Changes to This Disclaimer",
    content: `We reserve the right to modify or replace this Disclaimer at any time at our sole discretion.

If we make material changes to this Disclaimer, we will:
- Update the "Last Updated" date at the top of this page
- Provide notice through the Service or via email for significant changes

Your continued use of the Service after any changes to this Disclaimer constitutes your acceptance of such changes.

We encourage you to review this Disclaimer periodically for any updates.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99"
        />
      </svg>
    ),
  },
  {
    id: "contact",
    title: "10. Contact Us",
    content: `If you have any questions about this Disclaimer, please contact us:

Email: hello@nordict.com
Support: support@nordict.com


We aim to respond to all inquiries within 5 business days.`,
    icon: (
      <svg
        className="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75"
        />
      </svg>
    ),
  },
];
