# Generated by Django 5.2.9 on 2025-12-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='access_token_jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
