# Generated by Django 5.2.9 on 2025-12-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usersession_access_token_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_alerts_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_alerts_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_forecast_daily',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_forecast_significant',
            field=models.BooleanField(default=True),
        ),
    ]
