# Generated by Django 5.2.9 on 2025-12-30 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_notify_alerts_email_user_notify_alerts_push_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_active'], 'verbose_name': 'user session', 'verbose_name_plural': 'user sessions'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='api_key_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_horizon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_market',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_alerts_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_alerts_push',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_forecast_daily',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_forecast_significant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_started_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_ends_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_started_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_used',
        ),
        migrations.AlterField(
            model_name='usersession',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_market', models.CharField(default='BTC-USD', max_length=20)),
                ('default_horizon', models.CharField(default='daily', max_length=20)),
                ('notify_alerts_email', models.BooleanField(default=True)),
                ('notify_alerts_push', models.BooleanField(default=False)),
                ('notify_forecast_daily', models.BooleanField(default=True)),
                ('notify_forecast_significant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user preferences',
                'verbose_name_plural': 'user preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium'), ('teams', 'Teams')], default='free', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('trial_used', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('stripe_card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('stripe_card_exp_month', models.IntegerField(blank=True, null=True)),
                ('stripe_card_exp_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user subscription',
                'verbose_name_plural': 'user subscriptions',
                'db_table': 'user_subscriptions',
            },
        ),
    ]
