# Generated by Django 5.2.9 on 2025-12-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usersession_options_remove_user_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='pending_billing_cycle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='pending_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='pending_plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='pending_stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
